export const ADD_SEARCH_VALUE = 'ADD_SEARCH_VALUE';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_SEARCH_VALUE = 'FETCH_SEARCH_VALUE';
export const SHOW_NAVIGATE = 'SHOW_NAVIGATE';
export const FETCH_PAGE_FILTER = 'FETCH_PAGE_FILTER';
