export const ADD_SEARCH_VALUE = 'ADD_SEARCH_VALUE';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_SEARCH_VALUE = 'FETCH_SEARCH_VALUE';
export const FETCH_NEXT_VIDEOS = 'FETCH_NEXT_VIDEOS';
export const SHOW_NAVIGATE = 'SHOW_NAVIGATE';
export const FETCH_NEXT_PAGE = 'FETCH_NEXT_PAGE';
export const ADD_START_SCROLL = 'ADD_START_SCROLL';
export const ADD_MAX_RESULTS_VIDEOS = 'ADD_MAX_RESULTS_VIDEOS';
